#function in 7th day, exception still not understood properly
def name():
    print("Anjal Thapa")
name()